#!/usr/bin/env python3
"""Generate INDEX.md from the repository file tree.

Run from the repo root:
    python scripts/generate_index.py
"""

import os
from collections import defaultdict
from datetime import datetime

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SKIP_DIRS = {".git", "scripts", "__pycache__"}

DESCRIPTIONS = {
    ".lat": "Lattice Case Format",
    ".raw": "PSS/E Power Flow Data",
    ".epc": "PSLF Powerflow Case",
    ".pwb": "PowerWorld Binary Case",
    ".pwd": "PowerWorld Oneline Display",
    ".dyr": "PSS/E Dynamic Data",
    ".dyd": "PSLF Dynamic Data",
    ".aux": "PowerWorld Auxiliary File",
    ".con": "Contingency Data",
    ".gic": "GIC (Geomagnetically Induced Current) Data",
    ".idv": "PowerWorld IDV File",
    ".bsg": "PowerWorld Base Generation",
    ".tsb": "PowerWorld Transient Stability",
    ".m": "MATPOWER / MATLAB Case",
    ".json": "JSON Data",
    ".csv": "CSV Data",
    ".xlsx": "Excel Spreadsheet",
    ".py": "Python Script",
    ".txt": "Text File",
    ".md": "Markdown",
    ".jpg": "Image",
    ".zip": "Archive",
    ".docx": "Word Document",
    ".ini": "Configuration",
    ".rev": "Revision File",
    ".gitattributes": "Git Attributes",
}

# Ordered list of extensions for output sections.
# Extensions not listed here are appended alphabetically at the end.
SECTION_ORDER = [
    # Power flow
    ".lat", ".raw", ".epc", ".pwb", ".pwd",
    # Dynamics
    ".dyr", ".dyd",
    # Auxiliary / supplemental
    ".aux", ".con", ".gic", ".idv", ".bsg", ".tsb",
    # Scripts / data
    ".m", ".json", ".csv", ".xlsx", ".py",
    # Docs / other
    ".txt", ".md", ".jpg", ".docx", ".zip", ".ini", ".rev",
]


def collect_files():
    """Walk the repo and return {ext_lower: [relative_paths]}."""
    groups = defaultdict(list)

    for dirpath, dirnames, filenames in os.walk(REPO_ROOT):
        # Prune skipped directories
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]

        for fname in filenames:
            full = os.path.join(dirpath, fname)
            rel = os.path.relpath(full, REPO_ROOT).replace("\\", "/")

            _, ext = os.path.splitext(fname)
            if ext:
                key = ext.lower()
            else:
                key = "(no extension)"

            groups[key].append(rel)

    # Sort file lists
    for key in groups:
        groups[key].sort(key=str.lower)

    return groups


def ordered_keys(groups):
    """Return extension keys in display order."""
    keys = []
    for ext in SECTION_ORDER:
        if ext in groups:
            keys.append(ext)
    # Append any remaining extensions alphabetically
    for ext in sorted(groups.keys()):
        if ext not in keys:
            keys.append(ext)
    return keys


def build_summary_table(groups, keys):
    """Build a markdown summary table."""
    lines = []
    lines.append("| Extension | Type | Count |")
    lines.append("|-----------|------|-------|")
    for ext in keys:
        desc = DESCRIPTIONS.get(ext, "")
        count = len(groups[ext])
        lines.append(f"| `{ext}` | {desc} | {count} |")
    return "\n".join(lines)


def build_sections(groups, keys):
    """Build per-extension sections with file listings."""
    lines = []
    for ext in keys:
        desc = DESCRIPTIONS.get(ext, "")
        heading = f"`{ext}`"
        if desc:
            heading += f" — {desc}"
        lines.append(f"### {heading}")
        lines.append("")
        for path in groups[ext]:
            lines.append(f"- `{path}`")
        lines.append("")
    return "\n".join(lines)


def main():
    groups = collect_files()

    # Exclude INDEX.md and README.md from the index itself
    for ext in list(groups.keys()):
        groups[ext] = [p for p in groups[ext] if p not in ("INDEX.md", "README.md")]
        if not groups[ext]:
            del groups[ext]

    keys = ordered_keys(groups)

    total_files = sum(len(groups[k]) for k in keys)
    total_types = len(keys)
    timestamp = datetime.now().strftime("%Y-%m-%d")

    output = f"""\
# File Index

> Auto-generated by `scripts/generate_index.py` on {timestamp}.
> To regenerate: `python scripts/generate_index.py`

**{total_files}** files across **{total_types}** file types.

## Summary

{build_summary_table(groups, keys)}

## Files by Type

{build_sections(groups, keys)}"""

    index_path = os.path.join(REPO_ROOT, "INDEX.md")
    with open(index_path, "w", encoding="utf-8") as f:
        f.write(output)

    print(f"INDEX.md generated: {total_files} files, {total_types} types")


if __name__ == "__main__":
    main()
